# Generated by Django 4.2.5 on 2026-06-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
        ('billing', '0002_data_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
